//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pangolin.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pangolin.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;characters&quot;: [
        ///    { &quot;hex&quot;: &quot;000A&quot;, &quot;combination&quot;: &quot;&quot;, &quot;id&quot;: 10, &quot;displayHex&quot;: &quot;240A&quot; }, // Printable ASCII start
        ///    { &quot;hex&quot;: &quot;0020&quot;, &quot;combination&quot;: &quot;&quot;, &quot;id&quot;: 32, &quot;displayHex&quot;: &quot;2420&quot; },
        ///    { &quot;hex&quot;: &quot;0021&quot;, &quot;combination&quot;: &quot;&quot;, &quot;id&quot;: 33, &quot;displayHex&quot;: null },
        ///    { &quot;hex&quot;: &quot;0022&quot;, &quot;combination&quot;: &quot;&quot;, &quot;id&quot;: 34, &quot;displayHex&quot;: null },
        ///    { &quot;hex&quot;: &quot;0023&quot;, &quot;combination&quot;: &quot;&quot;, &quot;id&quot;: 35, &quot;displayHex&quot;: null },
        ///    { &quot;hex&quot;: &quot;0024&quot;, &quot;combination&quot;: &quot;&quot;, &quot;id&quot;: 36, &quot;displayHex&quot;: null },
        ///    { &quot;hex&quot;: &quot;0025&quot;, &quot;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string codePage {
            get {
                return ResourceManager.GetString("codePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the
        ///of
        ///and
        ///to
        ///in
        ///for
        ///is
        ///on
        ///that
        ///by
        ///this
        ///with
        ///you
        ///it
        ///not
        ///or
        ///be
        ///are
        ///from
        ///at
        ///as
        ///your
        ///all
        ///have
        ///new
        ///more
        ///an
        ///was
        ///we
        ///will
        ///home
        ///can
        ///us
        ///about
        ///if
        ///page
        ///my
        ///has
        ///search
        ///free
        ///but
        ///our
        ///one
        ///other
        ///do
        ///no
        ///information
        ///time
        ///they
        ///site
        ///he
        ///up
        ///may
        ///what
        ///which
        ///their
        ///news
        ///out
        ///use
        ///any
        ///there
        ///see
        ///only
        ///so
        ///his
        ///when
        ///contact
        ///here
        ///business
        ///who
        ///web
        ///also
        ///now
        ///help
        ///get
        ///view
        ///online
        ///first
        ///am
        ///been
        ///would
        ///how
        ///were
        ///me
        ///services
        ///some
        ///these
        ///click
        ///its
        ///like
        ///service
        ///than [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dictionary {
            get {
                return ResourceManager.GetString("dictionary", resourceCulture);
            }
        }
    }
}
